version: '3.7'
services:
  gocompiler:
    build:
      context: .
      dockerfile: ./containers/gocompiler/Dockerfile
    volumes:
      - ./src/backends:/app
      - ./src/backends/vendor_bin:/go/bin
